# vim ft=yaml
# travis-ci.org definition for DueCredit build
language: python
python:
  - "2.7"
#  - "3.2"
  - "3.3"
  - "3.4"
#  - "pypy"
#  - "pypy3"
before_install:
  # - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then travis_retry sudo apt-get update -qq; fi

git:
  depth: 99999

install:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy ]] ; then dpkg --compare-versions $(pypy --version 2>&1 | awk '/PyPy/{print $2;}') ge 2.5.1 || { d=$PWD; cd /tmp; wget --no-check-certificate https://bitbucket.org/pypy/pypy/downloads/pypy-2.5.1-linux64.tar.bz2; tar -xjvf pypy*bz2; cd pypy-*/bin/; export PATH=$PWD:$PATH; cd $d; } ; fi
  - travis_retry pip install -q coveralls 
  - pip install -r requirements.txt
  - python setup.py --help # just to trigger generation of .version
  - pip install -e .

script:
  - nosetests --with-doctest --with-cov --cover-package duecredit --logging-level=INFO
  - sudo `which python` setup.py install  # test installation

after_success:
  - coveralls
